Repository Rayy-007/meals-on-wheel-project, pull requests merged in 2023-12, with the labels that each got.

#5 Implemented Home Page By Min Khant!
  src/assets/volunteers/get-food-man.png
  src/assets/volunteers/login.png
  src/assets/volunteers/perform-team.png
  src/assets/volunteers/prepare-donation.png
  src/assets/volunteers/register.png
  src/assets/volunteers/volunteers.png
  src/components/ImagesImport.js
  src/components/about/About.jsx
  src/components/about/about.css
  src/components/home/Home.jsx
  src/components/home/home.css
  src/components/home/meal-service/MealService.jsx
  src/components/home/meal-service/mealService.css
  src/components/home/testimonial/Testimonial.jsx
  src/components/home/testimonial/testimonial.css
  src/components/util/footer/Footer.jsx
  src/components/util/footer/footer.css
  src/main.css
Labels: Implement

#8 Implemented pages by Min Khant
  src/App.jsx
  src/assets/people/old-man-1.jpg
  src/assets/people/old-woman-1.jpg
  src/assets/people/old-woman-2.jpg
  src/assets/safety/certificate.png
  src/assets/safety/safety-1.png
  src/assets/safety/safety-2.png
  src/components/ImagesImport.js
  src/components/management/foodSafety/FoodSafety.jsx
  src/components/management/foodSafety/foodsafety.css
  src/components/register/Register.jsx
  src/components/users/caregiver/Caregiver.jsx
  src/components/users/caregiver/caregiver.css
  src/components/users/meals/Meals.jsx
  src/components/users/meals/frozenmeals.js
  src/components/users/meals/hotmeals.js
  src/components/users/meals/meal.css
  src/components/users/volunteer/Volunteer.jsx
  src/components/users/volunteer/volunteer.css
  src/components/util/navbar/Navbar.jsx
  src/components/util/navbar/navbar.css
  src/main.css
Labels: Implement

#9 implemented feedback page by Min Khant
  src/App.jsx
  src/components/management/feedback/Feedback.jsx
  src/components/management/feedback/feedback.css
Labels: Implement

#11 Fixed Login and Contact #10
  src/assets/icons/send-arrow.png
  src/components/ImagesImport.js
  src/components/contact/Contact.jsx
  src/components/contact/contact.css
  src/components/login/Login.jsx
  src/components/login/login.css
  src/main.css
Labels: bug, enhancement

#15 Fixed Register Pages By Min Khant
  src/App.jsx
  src/assets/icons/partner.png
  src/components/ImagesImport.js
  src/components/register/Register.jsx
  src/components/register/RegisterCareGiver.jsx
  src/components/register/RegisterMember.jsx
  src/components/register/RegisterPartner.jsx
  src/components/register/RegisterVolunteer.jsx
  src/components/register/backColor.jpg
  src/components/register/get-meal-icon.png
  src/components/register/register-photo.png
  src/components/register/register.css
  src/main.css
Labels: bug, enhancement, good first issue

#17 Fixed Styling of Pages
  src/App.jsx
  src/components/about/About.jsx
  src/components/home/Home.jsx
  src/components/home/home.css
  src/components/register/Register.jsx
  src/components/util/footer/Footer.jsx
  src/components/util/footer/footer.css
  src/components/util/navbar/Navbar.jsx
Labels: enhancement

#19 Fixed Admin Route and Styling
  src/App.jsx
  src/components/management/admin/Admin.jsx
  src/components/management/admin/Members.jsx
  src/components/management/admin/admin.css
  src/components/management/delivery/Delivery.jsx
Labels: bug, enhancement

#20 implemented member fetch data
  src/App.jsx
  src/components/register/RegisterMember.jsx
  src/dataFetch/MapComponent.jsx
  src/dataFetch/memberData.js
Labels: Implement

#22 Making register to be connecting with backend.
  src/App.jsx
  src/components/register/RegisterCareGiver.jsx
  src/components/register/RegisterPartner.jsx
  src/components/register/RegisterVolunteer.jsx
  src/dataFetch/caregiverData.js
  src/dataFetch/partnerData.js
  src/dataFetch/volunteerData.js
Labels: Implement

#27 Fixed formatting and styling of the pages
  src/App.jsx
  src/components/donate/DonationForm.jsx
  src/components/login/AuthContext.jsx
  src/components/login/Login.jsx
  src/components/login/login.css
  src/components/management/admin/Dontators.jsx
  src/components/management/admin/Parners.jsx
  src/components/management/admin/Riders.jsx
  src/components/management/admin/Volunteers.jsx
  src/components/register/Register.jsx
  src/components/register/RegisterCareGiver.jsx
  src/components/register/RegisterPartner.jsx
  src/components/register/RegisterVolunteer.jsx
  src/components/register/register.css
Labels: enhancement

#34 Added Authorization and Authentication Navbar & More
  src/App.jsx
  src/Layout.jsx
  src/assets/profile/admin-profile.png
  src/assets/profile/caregiver-profile.png
  src/assets/profile/member-profile.png
  src/assets/profile/partner-profile.png
  src/assets/profile/rider.png
  src/assets/profile/volunteer-profile.png
  src/components/ImagesImport.js
  src/components/PagesImport.js
  src/components/login/Login.jsx
  src/components/management/partner/MealUpload.jsx
  src/components/register/Register.jsx
  src/components/register/RegisterCareGiver.jsx
  src/components/register/RegisterMember.jsx
  src/components/register/RegisterPartner.jsx
  src/components/register/RegisterVolunteer.jsx
  src/components/util/footer/Footer.jsx
  src/components/util/navbar/NavbarAdmin.jsx
  src/components/util/navbar/NavbarCareGiver.jsx
  src/components/util/navbar/NavbarMember.jsx
  src/components/util/navbar/NavbarPartner.jsx
  src/components/util/navbar/NavbarRider.jsx
  src/components/util/navbar/NavbarVolunteer.jsx
  src/components/util/navbar/navbar.css
  src/main.css
Labels: bug, enhancement, good first issue, question, Implement
